version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: retail-postgres
    environment:
      POSTGRES_DB: retail_db
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - retail-network

  app:
    build: .
    container_name: retail-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/retail_db
      SPRING_DATASOURCE_USERNAME: retail_user
      SPRING_DATASOURCE_PASSWORD: retail_password
    networks:
      - retail-network

volumes:
  postgres_data:

networks:
  retail-network:
    driver: bridge